[package]
name = "eudccdec"
version = "0.2.0"
authors = ["Daniele Tricoli <eriol@mornie.org>"]
license="GPL-3.0-only"
edition = "2021"


[dependencies]
anyhow = "1.0.41"
base45 = "3.0.0"
ciborium = "0.2.0"
flate2 = "1.0.20"
serde = "1.0.126"
